class Target_list:
    list_targets = ["@alefrotabrasil", "@jeanwyllys_real", "@rafinhabastos", "@paradasp", "@TodosFeministas", 
    "@RachelSherazade", "@OdeCarvalho ", "@roxmo", "@lobaoeletrico", "@PretaGil", "@ManuelaDavila", 
    "@zehdeabreu", "@lelispatricia", "@mamaefalei", "@sociaIismo", "@odiodobem", "@felipeneto", 
    "@mariadorosario", "@jairbolsonaro", "@DaniloGentili", "@ptbrasil", "@PSDBnaCamara", "@PSL_Nacional", 
    "@joicehasselmann", "@larimanoela", "@Haddad_Fernando", "@FlavioBolsonaro", "@SF_Moro", "@jandira_feghali", 
    "@LGBT_BR", "@ronnieromanini", "@wesleymasche", "@fredreadit", "@wesleymasche", "@Deknany", 
    "@sergio9554", "@martha_matos", "@alvanircarvalho", "@MadMaktub_", "@almeidaitaguai", "@jogolegal", 
    "@pensarepreciso", "@JoaquimMarioFe2", "@MirianSDSouza", "@CleideFagundes6", "@ThaynaraOG", 
    "@LucasRanngel", "@VEJA", "@cartacapital", "@gaybrasil", "@_feboorges", "@caldeiraodohuck", "@luansantana", 
    "@micheltelo", "@PaulaFernandes7","@eduardocosta", "@McPocahontasBR", "@JStelman2", "@gabilyoficial", 
    "@ffc_mand", "@falaloh", "@NegodoBorel", "@kevinho", "@Ludmilla", "@lucaslucco", "@xuxameneghel", 
    "@mariruybarbosa", "@fbbreal", "@RedeGlobo", "@gio_antonelli", 
    "@dedesecco", "@brunogagliasso", "@SBTonline", "@celsoportiolli", "@Eliana", "@SandyLeah", "@Fiuk", "@WanessaCamargo", "@Junior_Lima", 
    "@ANAMARIABRAGA", "@marcosmion", "@PBiaL", "@boninho", "@mariagadu", "@ValescaOficial", "@gilbertogil", 
    "@caetanoveloso", "@UOLNoticias", "@jose_simao", "@TatiQBOficial", "@mc_caroloficial", "@evaristocosta", 
    "@Estadao", "@RevistaISTOE", "@GloboNews", "@MiriamLeitaoCom", "@RevistaEpoca", "@EstadaoPolitica", 
    "@STF_oficial", "@STJnoticias", "@MPF_PGR", "@policiafederal", "@OGloboPolitica", "@planalto", 
    "@SenadoFederal", "@camaradeputados", "@DHumanosBrasil", "@sgovpr", 
    "@UOL", "@BlogdoJuca", "@galvaobueno", "@jornalnacional", "@ConversaAfiada", "@BruMarquezine", "@neymarjr", "@Tatawerneck", "@calabresadani", 
    "@MarceloAdnet", "@FabioPorchat", "@portadosfundos", "@g1", "@Anitta", "@emicida", "@patriciapillar", 
    "@MidiaNINJA", "@MST_Oficial", "@uneoficial", "@vanessa_grazz", "@mtst", "@ubesoficial","@levantepopular", 
    "@POVOsemMEDO", "@frentebrasilpop", "@luizaerundina", "@fernandapsol", "@UJSBRASIL", "@J_LIVRES", 
    "@PTnaCamara", "@inst_lula", "@PresidenBr", "@onyxlorenzoni", "@conexaopolitica", "@RenovaMidia", 
    "@PolitzOficial", "@aguedescartoon", "@SorayaThronicke", "@reaconaria", "@VemPraRua_br", "@brasil_paralelo", 
    "@gleisi", "@cirogomes", "@LSabatella", "@chico_pinheiro", "@anapaulaaraujo", "@CesarTralli", 
    "@giulianamorrone", "@beltraomaria", "@carlavilhenaa", "@mariana_godoy", 
    "@MonicaWaldvogel", "@olazaroramos", "@taisdeverdade", "@cleooficial", "@Julianaalvesiam", "@debranascimento", "@cissa_guimaraes", "@LuluSantos", 
    "@zcloficial", "@GalCosta", "@robertocarlos", "@zdoficial", "@carlinhosbrown", 
    "@ivetesangalo", "@danielamercury", "@ClaudiaLeitte", "@marcoluque", "@MarceloTas", "@CaioCastro", "@Pitty", 
    "@Castelli_Henri", "@ahickmann","@Joelma", "@SabrinaSato", "@rick_nandatico", 
    "@Fernanda_Gentil", "@brunalinzmeyer", "@sigaanacarolina", "@WesleySafadao", "@mcguime", "@louieponto", "@pinhodepietra", 
    "@coelhothali", "@natalyneri", "@LeticiaColin", "@leticiaspiller", "@sophiaabrahao", "@alexandregarcia", 
    "@MBLivre", "@pefabiodemelo", "@antunes_arnaldo", "@GiLancellotti", "@simasrodrigo", "@juulianapaiva", 
    "@brunavieira", "pablo vittar", "@programapanico", "@alenegrini", "@chicobarney", "@mauriciostycer", "@rosana", 
    "@Teledramaturgia", "@PatriciaKogut", "@aguinaldaosilva", "@euandremarques", "@brunodeluca", 
    "@TomCavalcante1", "@otaviano", "@patriciapoetap", "@omarciusmelhem", "@IngridGuimaraes", "@oserginho", 
    "@mellisboaalves", "@luizatomeofic", "@GalisteuOficial", "@TiciPinheiro", "@Ancelmocom", 
    "@gloriafperez", "@WalcyrCarrasco", "@fefito", "vanessa urach", "@jojotodynhoofc", "@eueduramos", "@pablovillaca", 
    "@anapaularenault", "@MunikBarbosa", "@thiago_p", "@Aguinaldinho", "@eduardomoreira", "@Jujuca1987", 
    "@RegianeAlves", "@paolla", "@Camiqueirozreal", "@gloriapires", "@cortezrafa", "@OscarFilho", "@taliriapetrone", 
    "@MarielleVIVEMOS", "@aeciodepapelao", "@diImabr", "@ttmionzinho", "@gusttavo_lima", 
    "@rodpocket", "@Itspedrito", "@perolafaria", "@benifalcone", "@whindersson", "@Christian_fig", "@luscas", "@cleytu", 
    "@luanlovato", "@OCriador", "@sensacionalista", "@malvados", "@LaerteCoutinho1", "@gifsdegatinhos", 
    "@textoscrueis", "@UmFilosofoCitou", "@_Filosofei", "@SoVibePositiva", "@MariliaMReal", "@Pontifex_pt", 
    "@BispoMacedo", "@IgrejaUniversal", "@majutrindade", "@gustastockler", "@NetflixBrasil", "@BancodoBrasil", 
    "@Caixa", "@itau", "@Bradesco", "@cocielo", "@JudeuDoZap", "@pemarcelorossi","@padremanzotti", "@cellbit",
    "@feeeelps", "@alanzoka", "@PkCanadianGuy", "@SaikoMene", "@ykuuro", "@Vito_Palmito", "@JakePudding_", 
    "@nilmoretto", "@Damianizando", "@LoiraNoob", "@rezende_evil", "@BRKsEDU", "@FunkyBlackCat", "@marcogomez_", 
    "@monark", "@jovemnerd", "@desimpedidos", "@cauemoura", "@marcoscastro", "@juzao", "@YgorFremo", 
    "@mkarolqueiroz", "@MikeLink1", "@peqitw", "@EmigeDaniel", "@EduKof", "@PortugaPC", "@g0ulaarte", 
    "@guselect", "@dokebu", "@SrWilsonCCA", "@Velberan", "@Fiaspo", "@Canal_90", "@AssopraFita", "@Calango", "@mateiformiga", 
    "@mucamuricoca", "@williangordox", "@fravineas", "@queenbriny", 
    "@Gabruxona", "@caju_sz", "@Riyuuka_", "@kyurenii", "@biancalula", "@Tawnaa_", "@Nycts_", "@t3ddyyyyy", "@FeCastanhari", 
    "@LubaTV", "@Luizagcarvalho", "@MiiEDB", "@gabicattuzzo", "@bellafusch", "@DianaZuski", "@marciliovi", 
    "@IsadoraBasile"]

